version: '2'

services:
  redis:
    image: redis:3

  mongo:
    image: mongo:3.0

  node:
    image: node:argon
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
    command: npm run test:watch
